### ISSUE TITLE
mistake in assemblyJarName

### ISSUE THREAD

**Issue by alkersan** [sbt/sbt-multi-jvm#17]
Maybe I'm missing something, but since v0.3.9 [assemblyJarName](https://github.com/sbt/sbt-multi-jvm/blob/v0.3.9/src/main/scala/com/typesafe/sbt/SbtMultiJvm.scala#L140) seems to be set incorrectly. It's defined as:
```scala
assemblyJarName in assembly := {
  name + "_" + scalaVersion + "-" + version + "-multi-jvm-assembly.jar"
}
```
which produces cryptic name 
`sbt.SettingKey$$anon$4@3b32763a_sbt.SettingKey$$anon$4@35f58f2c-sbt.SettingKey$$anon$4@31ca1d4a-multi-jvm-assembly.jar` because `name`, `version` and `scalaVersion` aren't *`Strings`* but *`Settings`*

I think intention was something like this:
```scala
assemblyJarName in assembly := s"${name.value}_${scalaVersion.value}-${version.value}-multi-jvm-assembly.jar"
```

**Comment by 2m** [comment]
Fixed by #19.
