### ISSUE TITLE
Don't put symbol with name `java` into autoimports

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt-multi-jvm#22]
Otherwise, all build files break that use fully qualified identifiers to something like `java.io.File` because of the ambiguity introduced by the autoimport.

**Comment by stevejagodzinski** [comment]
Is there any workaround for this?

Once I add addSbtPlugin("com.typesafe.sbt" % "sbt-multi-jvm" % "0.3.11") to my project\plugins.sbt, I am unable to resolve java.io.File from build.sbt

**Comment by stevejagodzinski** [comment]
In case anyone else comes across this issue. See following workaround:

1) Create project/FrqBuildFile.scala (same folder as build.sbt)
```scala
object FrqBuildFile {
	class FrqBuildFile(pathname: String) extends java.io.File(pathname)
}
```

2) In build.sbt use new FrqBuildFile instead of new File
```scala
import FrqBuildFile._

lazy val userHome = SettingKey[File]("user-home", "The user's home directory: ~", AMinusSetting)
userHome := new FrqBuildFile(System.getProperty("user.home"))
externalIvySettings(userHome(_ / "/.ivy2/ivysettings.xml"))
```

**Comment by dwijnand** [comment]
For creating files you can use the `file` method, eg. `file(sys props "user.home")`.

For accessing packages inside the java package you can use `_root_.java`, eg. `_root_.java.nio.file.Files`.
