### ISSUE TITLE
Jar not available in any repositories

### ISSUE THREAD

**Issue by velvia** [sbt/sbt-multi-jvm#24]
I just added this to project/plugins.sbt:

    addSbtPlugin("com.typesafe.sbt" % "sbt-multi-jvm" % "0.3.11")

And it cannot be found in any repos...

```
[error] Server access Error: Operation timed out url=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[error] Server access Error: Operation timed out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[warn] 	module not found: com.typesafe.sbt#sbt-multi-jvm;0.3.11
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/evan/.ivy2/local/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-multi-jvm_2.10_0.13/0.3.11/sbt-multi-jvm-0.3.11.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/typesafe/sbt/sbt-multi-jvm_2.10_0.13/0.3.11/sbt-multi-jvm-0.3.11.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-multi-jvm;0.3.11: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-multi-jvm:0.3.11 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.sbt:sbt-multi-jvm:0.3.11 (scalaVersion=2.10, sbtVersion=0.13) (/Users/evan/src/github/FiloDB/project/plugins.sbt#L7-8)
[warn] 		  +- default:filodb-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
```

**Comment by velvia** [comment]
If I look in the repo.typesafe.com, which redirects to dl.bintray.com, it does not contain that artifact, though it contains others.

https://dl.bintray.com/typesafe/ivy-releases/com.typesafe.sbt/

**Comment by 2m** [comment]
It is published to a separate bintray repo here: https://bintray.com/sbt-multi-jvm/sbt-plugins/sbt-multi-jvm

However that repo is linked to https://bintray.com/sbt/sbt-plugin-releases so it can be resolved from sbt builds without any additional resolvers.

It looks like in your case there was an intermitted network failure as indicated by:
```
[error] Server access Error: Operation timed out url=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
[error] Server access Error: Operation timed out url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-multi-jvm/scala_2.10/sbt_0.13/0.3.11/ivys/ivy.xml
```

**Comment by velvia** [comment]
@2m thanks, seems to be working now.   I would highly recommend Akka docs be updated to point at the latest sbt-multi-jvm though, they point at 0.3.8 which is old and conflicts with newer versions of sat-assembly.

**Comment by 2m** [comment]
I am glad it is working now. Would you be able and willing to open a PR fixing that older version number?

**Comment by velvia** [comment]
Oh, perhaps….  what are the instructions / is the Akka docs site in the same repo?

**Comment by 2m** [comment]
Akka docs source code are here https://github.com/akka/akka/tree/master/akka-docs 

You can create a PR there. Where did you find that version number? I was not able to find it after a cursory glance.

**Comment by velvia** [comment]
Sorry these are the Akks 2.3.15 docs.  

While I have you here, another QQ: where do the logs from the multi-jvm plugin tests or app runs go?

**Comment by 2m** [comment]
I see now. You are talking about this [page](http://doc.akka.io/docs/akka/snapshot/dev/multi-jvm-testing.html), which source code you can find [here](https://github.com/akka/akka/edit/master/akka-docs/rst/dev/multi-jvm-testing.rst). And source code says that the version of that plugin to display is taken from the actual [`plugins.sbt`](https://github.com/akka/akka/blob/master/project/plugins.sbt) files of the Akka project. So if you are willing you should create a PR for that file. :)

Anyway, regarding the logs: I do not think the logs are saved separately. They are all outputted to the console by sbt. Therefore I suggest you to checkout [sbt docs regarding logging](http://www.scala-sbt.org/0.13/docs/Howto-Logging.html). Maybe you'll find what you are looking for there.
