### ISSUE TITLE
Release (new) version with support for sbt 1.0.0

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-multi-jvm#33]

**Comment by ktoso** [comment]
Was merged but does not seem to be released? https://bintray.com/sbt-multi-jvm/sbt-plugins/sbt-multi-jvm#files/com.typesafe.sbt%2Fsbt-multi-jvm%2Fscala_2.10

**Comment by bantonsson** [comment]
Could we please also fix #22 before publishing an sbt 1.0 version?

**Comment by bantonsson** [comment]
Fixed by [v0.4.0](https://github.com/sbt/sbt-multi-jvm/releases/tag/v0.4.0)
