### ISSUE TITLE
Repeated builds eventually fail

### ISSUE THREAD

**Issue by kanishka-azimi** [sbt/sbt-multi-jvm#51]
I have a single multi-node test, which I run repeatedly in an sbt console, using `multi-jvm:test` . Sometimes, after multiple hours of repeated runs, the tests fail here:
```
[info] Compiling 1 Scala source to /<REDACTED>/target/scala-2.12/multi-jvm-classes...
[info] * <REDACTED>MultiNodeSpec
```
I'm unsure if the compiling or starting of the tests is hanging. I will add more details as I encounter this in the future. So far, I have seen this happen about 5 times in 2 months of development. It does not occur in our CI builds.

I speculate that a file is getting locked, which leads to a deadlock.

**Comment by raboof** [comment]
Might be something leaking somewhere - could you check (e.g. with visualvm) whether that is the case?

**Comment by raboof** [comment]
Indeed might be a file lock as well, perhaps take a stack dump?
