### ISSUE TITLE
sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-multi-jvm;sbtVersion=1.0;scalaVersion=2.12:0.4.0

### ISSUE THREAD

**Issue by rajcspsg** [sbt/sbt-multi-jvm#58]
sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-multi-jvm;sbtVersion=1.0;scalaVersion=2.12:0.4.0

I've project which uses sbt-multi-jvm. akka cluster version 2.6.17. I've updated version 2.6.18.

After update I get the below exception -

>    sbt clean compile test
>   [info] welcome to sbt 1.5.8 (Azul Systems, Inc. Java 11.0.12)
>   [info] loading global plugins from /Users/rajkumar.natarajan/.sbt/1.0/plugins
>   [info] loading project definition from /Users/rajkumar.natarajan/Documents/Coding/misc/akka-zk-cluster-seed/project/project
>   [info] loading settings for project project from project.sbt ...
>   [info] set current project to project (in build file:/Users/rajkumar.natarajan/Documents/Coding/misc/akka-zk-cluster-seed/project/)
>   [info] Executing in batch mode. For better performance use sbt's shell
>   [success] Total time: 0 s, completed Dec 23, 2021, 4:55:16 PM
>   [info] Updating 
>   [info] Resolved  dependencies
>   [warn] 
>   [warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
>   [warn]          com.typesafe.sbt:sbt-multi-jvm:0.4.0 (sbtVersion=1.0, scalaVersion=2.12)
>   [warn] 
>   [warn]  Note: Unresolved dependencies path:
>   [error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-multi-jvm;sbtVersion=1.0;scalaVersion=2.12:0.4.0
>   [error]   Not found
>   [error]   Not found
>   [error]   not found: /Users/rajkumar.natarajan/.ivy2/localcom.typesafe.sbt/sbt-multi-jvm/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
>   [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: https://repo.artima.com/releases/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: https://scala.jfrog.io/artifactory/sbt-plugin-releases/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: /Users/rajkumar.natarajan/.m2/repository/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   forbidden: https://mvnrepository.com/artifact/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
>   [error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
>   [error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
>   [error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
>   [error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
>   [error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
>   [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
>   [error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
>   [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
>   [error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
>   [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
>   [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
>   [error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
>   [error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
>   [error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
>   [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
>   [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
>   [error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
>   [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
>   [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
>   [error]         at sbt.Execute.work(Execute.scala:291)
>   [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
>   [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
>   [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
>   [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>   [error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>   [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>   [error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>   [error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>   [error]         at java.base/java.lang.Thread.run(Thread.java:829)
>   [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-multi-jvm;sbtVersion=1.0;scalaVersion=2.12:0.4.0
>   [error]   Not found
>   [error]   Not found
>   [error]   not found: /Users/rajkumar.natarajan/.ivy2/localcom.typesafe.sbt/sbt-multi-jvm/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
>   [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: https://repo.artima.com/releases/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: https://scala.jfrog.io/artifactory/sbt-plugin-releases/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   not found: /Users/rajkumar.natarajan/.m2/repository/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error]   forbidden: https://mvnrepository.com/artifact/com/typesafe/sbt/sbt-multi-jvm_2.12_1.0/0.4.0/sbt-multi-jvm-0.4.0.pom
>   [error] Total time: 2 s, completed Dec 23, 2021, 4:55:18 PM

How can I fix this exception?

**Comment by mjsmith707** [comment]
Did you end up fixing this? I deleted my cached copy and ran into the same thing. I didn't realize how old and unmaintained this plugin was :cold_sweat:

**Comment by rajcspsg** [comment]
I couldn't fix this error. But I remember it happens with akka 2.6.18. So we stayed in 2.6.17 itself. Perhaps try older version of akka and see if that works

**Comment by mkurz** [comment]
See #59

**Comment by mkurz** [comment]
Starting with version 0.5.0 the plugin is hosted on maven central:
- https://repo1.maven.org/maven2/com/github/sbt/sbt-multi-jvm_2.12_1.0/0.5.0/sbt-multi-jvm_2.12_1.0-0.5.0.pom
- https://github.com/sbt/sbt-multi-jvm/releases/tag/v0.5.0
