### ISSUE TITLE
Publish to Maven central using sbt-ci-release and groupId `com.github.sbt`

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-multi-jvm#59]
The artifacts of sbt-multi-jvm are only available on repo.scala-sbt.org currently which just had a multiple hours outage.

@eed3si9n if you add credentials I will add the pull request and then we should cut a new release.

- [x] Tell scala steward about migration https://github.com/scala-steward-org/scala-steward/pull/3266
- [x] Make scala steward come visit: https://github.com/VirtusLab/scala-steward-repos/pull/330

Fixes #58

**Comment by eed3si9n** [comment]
@mkurz Added creds, and also granted Admin rights to @sbt/play-team.

**Comment by mkurz** [comment]
@eed3si9n For some reasong `PGP_SECRET` and `PGP_PASSPHRASE` are missing: https://github.com/sbt/sbt-multi-jvm/settings/secrets/actions which makes the release fail: https://github.com/sbt/sbt-multi-jvm/actions/runs/7168117212/job/19515581734
Can you add them? Thanks!

**Comment by mkurz** [comment]
Ping @eed3si9n thanks!

**Comment by eed3si9n** [comment]
I guess I added credentials but did not generate a gpg key. If you are having trouble with it I can make one, but could you try and see if you can generate one plz?

**Comment by mkurz** [comment]
Hosted on maven central now:
- https://repo1.maven.org/maven2/com/github/sbt/sbt-multi-jvm_2.12_1.0/0.5.0/sbt-multi-jvm_2.12_1.0-0.5.0.pom
- https://github.com/sbt/sbt-multi-jvm/releases/tag/v0.5.0
