### ISSUE TITLE
JDK 21 doesn't appear to work for macos-latest

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-multi-jvm#83]
I am not sure why (I don't have access to logs), @mkurz maybe you can look into this? At worst we can just remove `macos-latest` from the CI, its highly likely that if this project works on Linux that it also works on Windows (mac is the most problematic one)

**Comment by mkurz** [comment]
I also couldn't access any logs. I restarted the the workflow and now it worked: https://github.com/sbt/sbt-multi-jvm/actions/runs/7622721261/job/20795026434
Seems like a temporary GitHub actions issue.
