### ISSUE TITLE
Cannot find sbt-multi-jvm 0.3.8 in any repository

### ISSUE THREAD

**Issue by asinduvg** [sbt/sbt-multi-jvm#89]
I was trying to build akka [v2.3.16](https://github.com/akka/akka/blob/v2.3.16/project/AkkaBuild.scala) and it requires multi-jvm 0.3.8. But it fails when I tried to compile it

<img width="874" alt="image" src="https://github.com/sbt/sbt-multi-jvm/assets/39031290/086f7062-9cad-4a03-8d06-00bfe73b3774">

**Comment by mkurz** [comment]
I have no idea where this was hosted in 2013:
- https://github.com/sbt/sbt-multi-jvm/releases/tag/release_0.3.8-sbt-0.13
- https://github.com/sbt/sbt-multi-jvm/releases/tag/release_0.3.8-sbt-0.12

sorry I can not help you here.
